### PR TITLE
Fix AppleClang build failure and implement retry on child process/command shell failure

### LINKED ISSUE #4: Compile failure with Apple clang due to stdc++fs reference
ShaderMake fails to compile with Apple clang due to an unneeded and invalid reference to stdc++fs on macOS.  Apple SDKs have included the `<filesystem>` library since Xcode 11 (which is old, we're at Xcode 15 now).

Also, ShaderMake threading using `popen()/pclose()` works on macOS just like linux, but there seems to be a resource limitation on the number of parallel command shell invocations, which is hard to determine from Apple docs.  This results in occasional pipe failures with compilation aborts on macOS when compiling 100s of shader combinations using threading.  Theoretically this could occur on any linux-like platform, it's just that current ShaderMake error handling does not recover from this.

I will submit a proposed fix for both issues.

### PR DESCRIPTION
**Pull request by SRSaunders**
Fixes #4

1. Removes reference to stdc++fs library when using AppleClang
2. Fixes clang compile warnings due to logical expression precedence issues
3. Implements error recovery with retry capability on child process and/or command shell failures when using `popen()` and `pclose()`.  Does not change behaviour for Windows SDK API-based compilation.  While the issue was observed on macOS, the solution is general and applies to all platforms: Windows, Linux, and macOS.  The retry capability allows a minimum of 10 retries (across all shader combos), up to a max of 5% failure rate which is quite generous.  I am not seeing anywhere near that failure rate - it's more like 2-3 failures across 350+ shader combinations.

### CODE REVIEW

**Comment by SRSaunders** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by apanteleev** [comment]
Thanks for the PR!

A few change requests:
- Add a command line argument to control the max number of retries, and I guess make it default to 0. Does the current logic mean that if there's a legit compile error, it will still retry?
- Break up the condition that starts with `(g_TaskRetryCount > 0 && ((result == -1 && error == ECHILD)` into something more readable.
- Use spaces for indentation in the modified fragments.

**Comment by SRSaunders** [comment]
Thanks for your comments.
1. I can add a command line argument with default value 0.  The current logic only retries on child process or command shell exec errors.  Legit compile errors will fail as before - no retries on those.
2. The strange logic is testing for: a) ECHILD errors (all platforms), and b) Command Shell (127) errors (posix only).  As far as I can tell, there is no symbolic representation for the 127 error code - although I will look again to make sure.  In any case I will break it up with some more comments to hopefully make this clearer.
3. I will change tabs to spaces.

**Comment by SRSaunders** [comment]
I have completed the changes as you suggested above.  I hope the logic update is more readable now.  I have added some comments plus a doc link discussing how to interpret `pclose()` status, which hopefully I have followed in my code.

I did alter one thing though, and that is the default `--retryCount` option which I set to 10 instead of 0.  Retries occur only under very specific circumstances relating to operating system pipe resource limits (I can observe `commandShellError` failures on macOS), or child process problems (i.e. `childProcessError` which I have not observed on any OS I have tested).  The retry conditions are not satisfied for normal shader compilation failures.  Given this, I felt that making the user set a retry count is a very under-the-covers thing akin to setting a retry count for network packet transmission or disk write verify failures.  This is not something I would normally expect a user to do.  While I have implemented the command line option to use if needed, I wouldn't normally want a user to have to set this.  For this reason I set the value to a reasonable number (10) which should hopefully cover most scenarios without the user getting involved in this low-level detail.  Your thoughts?

I have one additional question about defaults.  In your transition from shaderCompiler to ShaderMake, why did you change the defaults for `--tRegShift=0 --sRegShift=128 --bRegShift=256 --uRegShift=384`?  The new values are different (100, 200, 300, 400) and that initially caused me some problems in porting to the new ShaderMake tool.

**Comment by dzhdanNV** [comment]
>I have one additional question about defaults. In your transition from shaderCompiler to ShaderMake, why did you change the defaults for --tRegShift=0 --sRegShift=128 --bRegShift=256 --uRegShift=384? The new values are different (100, 200, 300, 400) and that initially caused me some problems in porting to the new ShaderMake tool.

I was done by me :D

**Comment by SRSaunders** [comment]
Thanks @dzhdanNV.  What was the reason for the change?  It broke my shaders until I restored the original values via command line options.

**Comment by dzhdanNV** [comment]
> What was the reason for the change?

It was my will. Users, including myself, should never rely on defaults and pass critical parameters explicitly.

**Comment by apanteleev** [comment]
Thanks, @SRSaunders! Merged.

>> why did you change the defaults

> It was my will. Users, including myself, should never rely on defaults and pass critical parameters explicitly.

More specifically, it was because [NRD](https://github.com/NVIDIAGameWorks/RayTracingDenoiser) uses those new offsets, yet they are still specified on the command line in its build system.

**Pull request merged**
